# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.87"

default_platform :ios

platform :ios do
  before_all do
    ENV["APP_ID"] = "com.carolanitz.voice-pitch-analyzer"
    ENV["KEYCHAIN"] = "github_keychain"
    ENV["PROJECT_PATH"] = "Voice Pitch Analyzer.xcodeproj"
    ENV["PROJECT_WORKSPACE"] = "Voice Pitch Analyzer.xcworkspace"
    ENV["SCHEME"] = "Voice Pitch Analyzer"

    create_keychain(
		  name: ENV["KEYCHAIN"],
		  password: ENV["APPLEID_PASSWORD"],
		  default_keychain: true,
		  unlock: true,
		  timeout: 3600,
		  lock_when_sleeps: false
    )
    
    unlock_keychain(
      path: ENV["KEYCHAIN"],
      password: ENV["APPLEID_PASSWORD"]
    )
    
  end

  desc "Submit to App Store"
  lane :release do

    disable_automatic_code_signing(
      path: ENV["PROJECT_PATH"]
    )

    sync_code_signing(
      type: "appstore",
      git_basic_authorization: Base64.strict_encode64(ENV["TOKEN_GITHUB"]),
      readonly: true,
      keychain_name: ENV["KEYCHAIN"],
      keychain_password: ENV["APPLEID_PASSWORD"]
    )
  
    update_project_team(
      path: ENV["PROJECT_PATH"],
      teamid: ENV["TEAM_ID"]
    )

    update_project_provisioning(
      xcodeproj: ENV["PROJECT_PATH"],
      profile: ENV["sigh_com.carolanitz.voice-pitch-analyzer_appstore_profile-path"],
      build_configuration: "Release",
      code_signing_identity: ENV["SIGNING_IDENTITY"]
    )

    update_provisioning_profile_specifier(
      new_specifier: 'match AppStore com.carolanitz.voice-pitch-analyzer',
      configuration: 'Release'
    )

    build_app(
      workspace: ENV["PROJECT_WORKSPACE"],
      scheme: ENV["SCHEME"],
      skip_profile_detection: true,
      export_options: {
        method: "app-store",
        configuration: "Release",
        codesigning_identity: ENV["SIGNING_IDENTITY"],
        provisioningProfiles: { 
          "com.carolanitz.voice-pitch-analyzer" => ENV["sigh_com.carolanitz.voice-pitch-analyzer_appstore_profile-name"],
        }
      }
    )

    upload_to_app_store

  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
