name: Release

# Trigger on PR and push to master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
  
    # pipe (|) for a multi-line command
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
      
    - name: Gem install
      run: gem install bundler:1.17.3
          
    - name: Install dependencies
      run: |
        bundle install
        bundle exec pod install
          
    - name: Swift build
      run: swift build -v
